openapi: 3.0.0
paths:
  /:
    get:
      operationId: AppController_getHello
      parameters: []
      responses:
        '200':
          description: ''
  /book/{id}:
    get:
      operationId: AppController_getBookById
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
  /book:
    get:
      operationId: AppController_getBooks
      parameters:
        - name: page
          required: true
          in: query
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json; charset=utf-8:
              schema:
                type: array
                items:
                  type: object
                  required: ['id', 'title', 'price']
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    price:
                      type: string
info:
  title: Backend
  description: Backend API definition
  version: '1.0'
  contact: {}
tags: []
servers: []
components:
  schemas: {}
