import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col  p-24">
          <Link href="/">
            <div className="text-2xl font-serif py-5">Book Store</div>
          </Link>
          {children}
        </main>
      </body>
    </html>
  );
}
